name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload to cPanel
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.coach-lewi.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Répertoire local à déployer
        server-dir: /portfoliocicd.coach-lewi.com/  # Répertoire distant sur cPanel
